import {createServer} from 'node:http';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {chromium} from 'playwright';import {encodeSegment,validSegment} from '../visual/transport.mjs';
const dir=path.resolve('sys/cache/transport-tests');await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true});
const server=createServer((req,res)=>res.end('<html></html>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);await page.setContent('<canvas id="film" width="1080" height="1920"></canvas>');await page.evaluate(()=>{window.renderFrame=async t=>{const c=document.querySelector('canvas').getContext('2d');c.fillStyle='#F7F4EB';c.fillRect(0,0,1080,1920);c.fillStyle='#071C24';c.fillRect(t*100,300,500,500);};});
 const equal=await page.evaluate(async()=>{await window.renderFrame(.2);const c=document.querySelector('canvas');const b=await new Promise(r=>c.toBlob(r,'image/png'));const bytes=new Uint8Array(await b.arrayBuffer());const a=Uint8Array.from(atob(c.toDataURL('image/png').split(',')[1]),c=>c.charCodeAt(0));return a.length===bytes.length&&a.every((v,i)=>v===bytes[i]);});assert.equal(equal,true);console.log('PASS exact PNG bytes binary vs base64');
 const file=dir+'/valid.mp4';const m=await encodeSegment(page,file,0,15);assert.equal(m.frames,15);assert.equal(await validSegment(file,15),true);assert.equal(m.maxInFlight,1);console.log('PASS bounded binary pipe and exact frame count');
 await fs.appendFile(file,'corruption');assert.equal(await validSegment(file,15),false);console.log('PASS checksum rejects corrupt cache');
 const bad={evaluate:async(fn,args)=>{const r=await fetch(args.endpoint+'?frame=9',{method:'POST',body:Buffer.from('invalid')});assert.equal(r.status,400);throw Error('out of order');}};
 await assert.rejects(()=>encodeSegment(bad,dir+'/order.mp4',0,15));assert.equal(await validSegment(dir+'/order.mp4',15),false);console.log('PASS out-of-order request never publishes');
 const interrupted={evaluate:async()=>{throw Error('simulated browser interruption');}};await assert.rejects(()=>encodeSegment(interrupted,dir+'/interrupted.mp4',0,15));assert.equal(await validSegment(dir+'/interrupted.mp4',15),false);console.log('PASS interrupted render never publishes');
 for(const [name,script] of [['encoder','#!/bin/sh\nexit 3\n'],['enospc','#!/bin/sh\nprintf "No space left on device\\n" >&2\nexit 1\n']]){const bin=dir+'/'+name;await fs.writeFile(bin,script,{mode:0o755});await assert.rejects(()=>encodeSegment(page,dir+'/'+name+'.mp4',0,15,{ffmpeg:bin}));assert.equal(await validSegment(dir+'/'+name+'.mp4',15),false);console.log('PASS simulated '+name+' failure never publishes');}
}finally{await browser.close();await new Promise(r=>server.close(r));}
