import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';
import {startServer} from '../visual/server.mjs';import {neutralProject} from '../examples/neutral.mjs';
const root=path.resolve(import.meta.dirname,'../../..'),work=path.join(root,'sys/cache/browser-test');await fs.mkdir(work,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',args:['--no-sandbox','--enable-unsafe-swiftshader']});const results=[];
async function check(name,project,fn){const file=path.join(work,'project.json'),tl=path.join(work,'timeline.json');await fs.writeFile(file,JSON.stringify(project));await fs.writeFile(tl,JSON.stringify({valid:true,errors:[],targetSeconds:3,fps:30,phrases:[]}));const {server,url}=await startServer(root,file,tl);const p=await browser.newPage({viewport:{width:1080,height:1920}});const errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p,url,errors);results.push({name,passed:true});}finally{await p.close();await server.close();}}
try{
 for(const palette of ['technology','creative'])for(const theme of ['light','dark']){
  const pr=neutralProject();pr.palette=palette;pr.theme=theme;
  await check(palette+'-'+theme,pr,async(p,url,errors)=>{await p.route('**/*.woff2',async route=>{await new Promise(r=>setTimeout(r,150));await route.continue();});await p.goto(url);await p.waitForFunction(()=>window.filmReady);assert.equal(await p.evaluate(()=>document.fonts.check('600 48px "Be Vietnam Pro"')),true);await p.evaluate(()=>window.renderFrame(2.5));await p.locator('#film').screenshot({path:path.join(work,palette+'-'+theme+'.png')});assert.deepEqual(errors,[]);});
 }
 await check('progressive-stroke-and-list',neutralProject(),async(p,url)=>{await p.goto(url);await p.waitForFunction(()=>window.filmReady);const frames=[];for(const t of [.8,1.1,1.4,2.5]){await p.evaluate(t=>window.renderFrame(t),t);frames.push(await p.evaluate(()=>document.querySelector('#film').toDataURL()));}assert.equal(new Set(frames).size,4);});
 const long=neutralProject();long.scenes[0].elements[0].children[0].items=['Một hành động rõ ràng, có thông tin đủ để thực hiện và kiểm tra kết quả','Dòng tiếp nối vẫn căn theo cột chữ'];
 await check('Vietnamese-wrapping',long,async(p,url,errors)=>{await p.goto(url);await p.waitForFunction(()=>window.filmReady);await p.evaluate(()=>window.renderFrame(2));assert.deepEqual(errors,[]);});
 const overflow=neutralProject();overflow.scenes[0].elements=[{id:'overflow',type:'text',text:'Một dòng rất dài phải xuống nhiều dòng',width:300,height:30,fontSize:44}];
 await check('overflow-fails',overflow,async(p,url,errors)=>{await p.goto(url);await p.waitForTimeout(6500);assert.ok(errors.some(e=>/overflow|exceeds width/.test(e)),JSON.stringify(errors));});
 const missing=neutralProject();missing.scenes[0].elements=[{id:'missing',type:'image',src:'missing.png'}];
 await check('missing-image-fails',missing,async(p,url,errors)=>{await p.goto(url);await p.waitForTimeout(6500);assert.notEqual(await p.evaluate(()=>window.filmReady),true);assert.ok(errors.length>0);});
 const camera=neutralProject();camera.scenes[0].elements=[{id:'paper',type:'projection',width:940,height:980,animate:{ry:[{at:0,value:-.4},{at:2,value:0}]},children:[{type:'panel',width:940,height:980,fill:'panel',children:[{id:'large',type:'text',text:'Một ý rõ ràng',x:80,y:300,fontSize:60}]}]}];
 await check('three-dimensional-camera',camera,async(p,url,errors)=>{await p.goto(url);await p.waitForFunction(()=>window.filmReady);await p.evaluate(()=>window.renderFrame(.1));const a=await p.evaluate(()=>document.querySelector('#film').toDataURL());await p.evaluate(()=>window.renderFrame(1.5));const b=await p.evaluate(()=>document.querySelector('#film').toDataURL());assert.notEqual(a,b);assert.deepEqual(errors,[]);});
 for(const palette of ['technology','creative'])for(const theme of ['light','dark']){const publication=neutralProject();publication.palette=palette;publication.theme=theme;publication.scenes[0].role='recap';publication.scenes[0].theme=theme;publication.publication={title:'Context window là gì?',primaryKeyword:'context window',seriesLabel:'CHAT AI CĂN BẢN',coverFrame:15,intro:{enabled:true,holdSec:1.5},outro:{enabled:true,avatarTheme:'scene',durationSec:3,renderTakeaways:true,takeaways:['Nhắc lại dữ kiện cần dùng trước khi hỏi','Kiểm tra câu trả lời']}};
 await check('publication-intro-cover-outro-'+palette+'-'+theme,publication,async(p,url,errors)=>{await p.goto(url);await p.waitForFunction(()=>window.filmReady);await p.evaluate(()=>window.renderFrame(0));const intro=await p.evaluate(()=>Array.from(document.querySelector('#film').getContext('2d').getImageData(100,310,1,1).data));assert.ok(intro[0]>50&&(intro[1]>80||intro[2]>120),'intro keyword chip should be visible at frame 0');await p.evaluate(()=>window.renderFrame(2.9));const outro=await p.evaluate(()=>Array.from(document.querySelector('#film').getContext('2d').getImageData(961,1390,1,1).data));assert.ok(outro[0]>120&&outro[1]>80,'outro avatar ring should be visible');assert.deepEqual(errors,[]);});}
}finally{await browser.close();await fs.writeFile(path.join(work,'results.json'),JSON.stringify(results,null,2));console.log(results);}
