import fs from 'node:fs/promises';import path from 'node:path';
import {intro,readyOutro,media,compose,run} from '../identity.mjs';
const root=path.resolve(import.meta.dirname,'../../..'),work=path.join(root,'sys/work/identity-demo'),out=path.join(root,'video/nhan-dien/ban-do-hoc-thuat');await fs.mkdir(work,{recursive:true});await fs.mkdir(out,{recursive:true});
const m=await readyOutro(),words=['AI bịa','Cửa sổ ngữ cảnh','Học từ phản hồi'],intros=[];
for(let i=0;i<words.length;i++){const dir=await intro(words[i]);intros.push(dir);await fs.copyFile(dir+'/intro.mp4',out+`/intro-${i+1}.mp4`);await fs.copyFile(dir+'/intro-cover.png',out+`/cover-${i+1}.png`);}
const seconds=6,timeline={valid:true,targetSeconds:seconds,fps:30,phrases:[]};
const p={id:'identity-demo',title:'Vẽ một ý tưởng',stylePreset:'net-cinematic-v1',rendererVersion:'1.0.0',layout:'drawing-first',captionMode:'sidecar',palette:'technology',format:{width:1080,height:1920,fps:30},audioMaster:'master.wav',scenes:[{id:'drawing',start:0,end:seconds,title:[],theme:'light',template:{id:'freehand',version:'1.0.0',items:[],drawings:[
 {id:'book',box:[240,600,600,500],path:'M 50 18 Q 22 0 3 9 L 3 86 Q 25 75 50 93 Q 75 75 97 86 L 97 9 Q 73 0 50 18 L 50 93',cue:0,endCue:3,color:'ink'},
 {id:'reading',box:[240,600,600,500],path:'M 15 27 L 38 34 M 15 43 L 38 50 M 63 34 L 86 27 M 63 50 L 86 43',cue:3,endCue:4.8,color:'teal'},
 {id:'insight',box:[470,395,140,140],path:'M 50 1 Q 55 45 99 50 Q 55 55 50 99 Q 45 55 1 50 Q 45 45 50 1',cue:4.8,endCue:6,color:'gold'}]}}]};
await fs.writeFile(work+'/project.json',JSON.stringify(p));await fs.writeFile(work+'/timeline.json',JSON.stringify(timeline));run('ffmpeg',['-y','-v','error','-f','lavfi','-i','anullsrc=r=48000:cl=mono','-t','6','-c:a','pcm_s16le',work+'/master.wav']);
run(process.execPath,['sys/engine/visual/render.mjs','--project',work+'/project.json','--timeline',work+'/timeline.json','--output',work,'--name','body']);
await compose([{file:intros[0]+'/intro.mp4',seconds:1.5,timeline:{targetSeconds:1.5,phrases:[]}},{file:work+'/body.mp4',seconds,timeline},{file:media+'/outro.mp4',seconds:m.seconds,timeline:JSON.parse(await fs.readFile(media+'/timeline.json'))}],out,'sample',intros[0]+'/intro-cover.png');
await fs.copyFile(media+'/outro.mp4',out+'/outro.mp4');await fs.copyFile(media+'/outro.srt',out+'/outro.srt');
await fs.writeFile(out+'/index.html',`<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bản đồ học thuật</title><style>body{background:#f7f4eb;color:#12363b;font:18px system-ui;max-width:1100px;margin:40px auto;padding:24px}h1{font-size:40px}section{display:flex;gap:24px;flex-wrap:wrap}article{flex:1;min-width:220px}video{width:100%;max-height:650px;background:#edece2;border-radius:14px}a{color:#176c68}small{display:block;margin:10px 0}</style><h1>Bản đồ học thuật</h1><p>Một nét mở đường. Một điểm khám phá.</p><section><article><h2>Mẫu ghép</h2><video controls playsinline preload="metadata" src="sample.mp4"></video><small>Intro → nét vẽ minh họa → outro. Phần giữa không có lời; outro dùng Adam.</small><a href="sample.srt">Phụ đề</a></article><article><h2>Outro dùng chung</h2><video controls playsinline preload="metadata" src="outro.mp4"></video></article></section><h2>Đổi từ khóa, giữ nhận diện</h2><section>${words.map((w,i)=>`<article><h3>${w}</h3><video controls playsinline preload="metadata" poster="cover-${i+1}.png" src="intro-${i+1}.mp4"></video><a href="cover-${i+1}.png">Ảnh bìa</a></article>`).join('')}</section></html>`);
console.log(out);
